//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Product
    {
        public int ID_Application { get; set; }
        public int ID_User { get; set; }
        public int ID_Pharmacy { get; set; }
        public int ID_Product { get; set; }
    
        public virtual Pharmcy Pharmcy { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
