//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmcy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pharmcy()
        {
            this.Application_Product = new HashSet<Application_Product>();
        }
    
        public int ID_Pharmacy { get; set; }
        public int ID_City { get; set; }
        public int ID_Strit { get; set; }
        public int ID_Home { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Product> Application_Product { get; set; }
        public virtual City City { get; set; }
        public virtual Home Home { get; set; }
        public virtual Strit Strit { get; set; }
    }
}
