//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Application_Product = new HashSet<Application_Product>();
        }
    
        public int ID_Product { get; set; }
        public string Name_Product { get; set; }
        public decimal Price { get; set; }
        public int ID_Category { get; set; }
        public string Contry_Manufacture { get; set; }
        public int Id_Warning { get; set; }
        public string Composition { get; set; }
        public string Sescription { get; set; }
        public string Indicatioin { get; set; }
        public string Contraindication { get; set; }
        public string Method_of_application { get; set; }
        public byte[] Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application_Product> Application_Product { get; set; }
        public virtual Category_Product Category_Product { get; set; }
        public virtual Warning Warning { get; set; }
    }
}
